### ISSUE TITLE
Starting Points of Animations

### ISSUE THREAD

**Issue by plisvb** [tictail/bounce.js#20]
Is it possible to have starting points for the animations?  for example, if I'm using the "jelly" preset, the animated elements animation starts at coordinates center center.  Can I change them to start top left for example. x:0 and y:0?

**Comment by JoelBesada** [comment]
You can always set the `transform-origin` (https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin) on your element to change this.

**Comment by plisvb** [comment]
yup, that works, thanks

**Comment by JoelBesada** [comment]
:+1:
