### ISSUE TITLE
Text inside the animated div is getting blurred 

### ISSUE THREAD

**Issue by iamgraviteja** [tictail/bounce.js#23]
When a div is animated using _Swoosh_  animation (example) , the text inside the div is getting blur and during the animation and getting set properly after the animation.

[Fiddle example](https://jsfiddle.net/iamraviteja/nd9xk9g2/1/)

**Comment by eltonmesquita** [comment]
@ravi2808 , this is an browser issue with 3d transforms, not with bounce.js or any other librarys. There are some way to minimize those problems, but it's not simple and usually lots of try and error attempts, like trying to add `backface-visibility: hidden;` to the element or its parent, playing with `text-rendering` property and other stuff.

There's no actual fix, as far as I know.
