### ISSUE TITLE
Naming animations

### ISSUE THREAD

**Issue by gpoitch** [tictail/bounce.js#7]
Great project!  To make copying and pasting the exported css easier, it would be nice to add a field to set the animation name so you don't have to change that in your code every time.  Also omit the `.animation-target {}` rule from the output and put that in some documentation instead.  This would make the workflow super efficient.  Thanks again, great job.

**Comment by qikkeronline** [comment]
Can't agree more. Awesome tool but this would make it much less tedious - thanks for considering it! :+1:
